//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsAnwoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsAnwoReference.IWsAnwo")]
    public interface IWsAnwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/consultar_productos_disponibles", ReplyAction="http://tempuri.org/IWsAnwo/consultar_productos_disponiblesResponse")]
        BuenosAires.Model.Respuesta consultar_productos_disponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/consultar_productos_disponibles", ReplyAction="http://tempuri.org/IWsAnwo/consultar_productos_disponiblesResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> consultar_productos_disponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/reservar_producto", ReplyAction="http://tempuri.org/IWsAnwo/reservar_productoResponse")]
        BuenosAires.Model.Respuesta reservar_producto(string nroserieanwo, string reservado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/reservar_producto", ReplyAction="http://tempuri.org/IWsAnwo/reservar_productoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> reservar_productoAsync(string nroserieanwo, string reservado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsAnwoChannel : BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAnwoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo>, BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo {
        
        public WsAnwoClient() {
        }
        
        public WsAnwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta consultar_productos_disponibles() {
            return base.Channel.consultar_productos_disponibles();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> consultar_productos_disponiblesAsync() {
            return base.Channel.consultar_productos_disponiblesAsync();
        }
        
        public BuenosAires.Model.Respuesta reservar_producto(string nroserieanwo, string reservado) {
            return base.Channel.reservar_producto(nroserieanwo, reservado);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> reservar_productoAsync(string nroserieanwo, string reservado) {
            return base.Channel.reservar_productoAsync(nroserieanwo, reservado);
        }
    }
}
