//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsStockProductoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsStockProductoReference.IWsStockProducto")]
    public interface IWsStockProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsStockProducto/obtener_equipos_en_bodega", ReplyAction="http://tempuri.org/IWsStockProducto/obtener_equipos_en_bodegaResponse")]
        BuenosAires.Model.Respuesta obtener_equipos_en_bodega();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsStockProducto/obtener_equipos_en_bodega", ReplyAction="http://tempuri.org/IWsStockProducto/obtener_equipos_en_bodegaResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> obtener_equipos_en_bodegaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsStockProductoChannel : BuenosAires.BodegaBA.WsStockProductoReference.IWsStockProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsStockProductoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsStockProductoReference.IWsStockProducto>, BuenosAires.BodegaBA.WsStockProductoReference.IWsStockProducto {
        
        public WsStockProductoClient() {
        }
        
        public WsStockProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsStockProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsStockProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsStockProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta obtener_equipos_en_bodega() {
            return base.Channel.obtener_equipos_en_bodega();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> obtener_equipos_en_bodegaAsync() {
            return base.Channel.obtener_equipos_en_bodegaAsync();
        }
    }
}
